/*
 * 389. Find the Difference
 *
 *
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Return the letter that was added to t.
 *
 * Example 1:
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 *
 * Example 2:
 * Input: s = "", t = "y"
 * Output: "y"
 *
 * Example 3:
 * Input: s = "a", t = "aa"
 * Output: "a"
 *
 * Example 4:
 * Input: s = "ae", t = "aea"
 * Output: "a"
 *
 * Constraints:
 *
 *     0 <= s.length <= 1000
 *     t.length == s.length + 1
 *     s and t consist of lowercase letters only.
 */









class FindDiff {
    public char findTheDifference(String s, String t) {
        int[] count = new int[26];

        for (char c : s.toCharArray()) count[c - 'a']++;
        for (char c : t.toCharArray()) count[c - 'a']--;

        for (int i = 0; i < 26; i++) {
            if (count[i] < 0) return (char)('a' + i);
        }

        return ' '; 
    }
}